# General configuration
user_dir: "~/.config/cala"
video_directory: "~/Library/Application Support/cala/videos"
video_files:
  - "sample1.mp4"
  - "sample2.mp4"
output_directory: "~/Library/Application Support/cala/output"
output_name: "cala"

# Pipeline configuration
pipeline_config:
  preprocess:
    downsample:
      transformer: "Downsampler" # Maps to Preprocessor.DOWNSAMPLE
      params:
        method: "mean"
        dimensions: [ "width", "height" ]
        strides: [ 2, 2 ]

    denoise:
      transformer: "denoise" # Maps to Preprocessor.DENOISE
      params:
        method: "gaussian"
        kwargs:
          ksize: [ 3, 3 ]
          sigmaX: 1.5
      requires: [ "downsample" ]

    background:
      transformer: "background_removal" # Maps to Preprocessor.BACKGROUND_REMOVAL
      params:
        method: "uniform"
        kernel_size: 3
      requires: [ "denoise" ]

  initialization:
    footprints:
      transformer: "footprints" # Maps to Initializer.FOOTPRINTS
      params:
        threshold_factor: 0.2
        kernel_size: 3
        distance_metric: "L2"
        distance_mask_size: 5
      n_frames: 3

    traces:
      transformer: "traces" # Maps to Initializer.TRACES
      params:
        component_axis: "components"
        frames_axis: "frame"
      n_frames: 3
      requires: [ "footprints" ]

  iteration:
    detect:
      transformer: "detect" # Maps to Iterator.DETECT
      params:
        threshold: 0.5
        min_distance: 10

    traces:
      transformer: "traces" # Maps to Iterator.TRACES
      params:
        window_size: 10
      requires: [ "detect" ]
