name: docs
on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        if: true # set to false if repo wants to go private
        with:
          project-slug: "cala"
